# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-23 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190817_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='comment',
            field=models.CharField(default=b'', max_length=256, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='trade_no',
            field=models.CharField(default=b'', max_length=128, verbose_name=b'\xe6\x94\xaf\xe4\xbb\x98\xe7\xbc\x96\xe5\x8f\xb7'),
        ),
    ]
